/**
 * mockData.js — All mock/seed data for TechVault
 *
 * LESSON: Separation of concerns
 * Components never hardcode data. Data lives in one place so it's easy
 * to swap mock data for a real API later. Your React components stay clean.
 */

export const CATEGORIES = [
  { id: 'all',        label: 'All Products',       icon: 'fa-boxes-stacked' },
  { id: 'laptops',    label: 'Laptops & PCs',      icon: 'fa-laptop' },
  { id: 'phones',     label: 'Phones & Tablets',   icon: 'fa-mobile-screen' },
  { id: 'audio',      label: 'Audio & Headphones', icon: 'fa-headphones' },
  { id: 'gaming',     label: 'Gaming',              icon: 'fa-gamepad' },
  { id: 'software',   label: 'Software & Licenses', icon: 'fa-code' },
  { id: 'networking', label: 'Networking',           icon: 'fa-wifi' },
  { id: 'cameras',    label: 'Cameras & Drones',    icon: 'fa-camera' },
  { id: 'wearables',  label: 'Wearables',            icon: 'fa-watch' },
  { id: 'components', label: 'PC Components',        icon: 'fa-microchip' },
]

export const VENDORS = [
  {
    id: 'v1', handle: 'NovaElectronics', initials: 'NE',
    gradient: 'from-cyan-500 to-blue-600',
    rating: 4.97, reviews: 3241, sales: 8420,
    satisfaction: 99.7, memberSince: 'Jan 2020',
    shipsFrom: 'United States', shipsFromFlag: 'US',
    deliveryTime: '2-3 days (US)',
    verified: true, express: true,
    bio: 'Premium electronics retailer specializing in cutting-edge laptops, GPUs, and workstation builds. All products ship with full manufacturer warranty.',
    specialties: ['Laptops', 'GPUs', 'Workstations', 'Peripherals'],
    stats: { processingSpeed:4.9, communication:4.8, shippingSpeed:4.9, packaging:5.0, productQuality:4.9 },
  },
  {
    id: 'v2', handle: 'PixelForge', initials: 'PF',
    gradient: 'from-violet-500 to-purple-700',
    rating: 4.95, reviews: 1872, sales: 5130,
    satisfaction: 99.4, memberSince: 'Mar 2021',
    shipsFrom: 'United Kingdom', shipsFromFlag: 'GB',
    deliveryTime: '3-5 days (EU)',
    verified: true, express: false,
    bio: 'Software, creative tools, and developer licenses. Instant digital delivery. Specializes in discounted professional and educational licenses.',
    specialties: ['Software Licenses', 'Dev Tools', 'Creative Suite', 'SaaS'],
    stats: { processingSpeed:5.0, communication:4.9, shippingSpeed:5.0, packaging:4.8, productQuality:4.9 },
  },
  {
    id: 'v3', handle: 'SoundLab', initials: 'SL',
    gradient: 'from-emerald-500 to-teal-600',
    rating: 4.92, reviews: 2647, sales: 6890,
    satisfaction: 98.9, memberSince: 'Jun 2019',
    shipsFrom: 'Germany', shipsFromFlag: 'DE',
    deliveryTime: '2-4 days (EU)',
    verified: true, express: true,
    bio: 'Top-rated audio specialist. From studio monitors to wireless earbuds — every product tested by in-house audio engineers before shipping.',
    specialties: ['Headphones', 'Studio Monitors', 'DACs/Amps', 'Earbuds'],
    stats: { processingSpeed:4.8, communication:4.9, shippingSpeed:4.7, packaging:5.0, productQuality:5.0 },
  },
  {
    id: 'v4', handle: 'GameCore', initials: 'GC',
    gradient: 'from-red-500 to-orange-600',
    rating: 4.89, reviews: 4210, sales: 11200,
    satisfaction: 98.2, memberSince: 'Sep 2018',
    shipsFrom: 'Japan', shipsFromFlag: 'JP',
    deliveryTime: '5-7 days (intl)',
    verified: true, express: false,
    bio: 'Direct import of gaming hardware, peripherals, and accessories from Japan. Exclusive titles and limited editions.',
    specialties: ['Gaming Peripherals', 'Consoles', 'Import Games', 'RGB Gear'],
    stats: { processingSpeed:4.7, communication:4.8, shippingSpeed:4.6, packaging:4.9, productQuality:5.0 },
  },
  {
    id: 'v5', handle: 'DroneWorks', initials: 'DW',
    gradient: 'from-sky-500 to-indigo-600',
    rating: 4.94, reviews: 981, sales: 2340,
    satisfaction: 100, memberSince: 'Nov 2022',
    shipsFrom: 'Canada', shipsFromFlag: 'CA',
    deliveryTime: '3-6 days',
    verified: true, express: true,
    bio: 'Cameras, drones, and imaging equipment for professionals. Every item ships with full documentation and accessories package.',
    specialties: ['Drones', 'Cameras', 'Lenses', 'Gimbals'],
    stats: { processingSpeed:5.0, communication:5.0, shippingSpeed:4.9, packaging:5.0, productQuality:4.9 },
  },
  {
    id: 'v6', handle: 'WearTech', initials: 'WT',
    gradient: 'from-pink-500 to-rose-600',
    rating: 4.88, reviews: 1540, sales: 3870,
    satisfaction: 98.6, memberSince: 'Feb 2023',
    shipsFrom: 'Australia', shipsFromFlag: 'AU',
    deliveryTime: '4-7 days',
    verified: false, express: false,
    bio: 'Smartwatches, fitness trackers, AR glasses, and the latest wearable tech. Sourced directly from manufacturers.',
    specialties: ['Smartwatches', 'Fitness Bands', 'AR Glasses', 'Health Monitors'],
    stats: { processingSpeed:4.8, communication:4.7, shippingSpeed:4.8, packaging:4.9, productQuality:4.9 },
  },
]

export const PRODUCTS = [
  {
    id: 'p1', vendorId: 'v1', vendorHandle: 'NovaElectronics',
    name: 'ASUS ProArt Studiobook 16 OLED',
    category: 'laptops', subcategory: 'Workstations',
    price: 1899, priceOld: 2199,
    description: 'OLED workstation laptop built for creators and developers. RTX 4070, Ryzen 9, and OLED Pantone-validated display.',
    icon: 'fa-laptop', iconColor: 'text-cyan-400',
    rating: 4.9, reviewCount: 312,
    inStock: true, featured: true, badge: 'Best Seller',
    specs: { Display:'16" 4K OLED 120Hz', CPU:'AMD Ryzen 9 7945HX', GPU:'RTX 4070 8GB', RAM:'32GB DDR5', Storage:'1TB NVMe SSD' },
  },
  {
    id: 'p2', vendorId: 'v4', vendorHandle: 'GameCore',
    name: 'Sony PlayStation 5 Pro Bundle',
    category: 'gaming', subcategory: 'Consoles',
    price: 649, priceOld: null,
    description: 'PS5 Pro with DualSense, 2 games, and 1-year PS Plus. Japan import with full English support.',
    icon: 'fa-gamepad', iconColor: 'text-red-400',
    rating: 4.98, reviewCount: 891,
    inStock: true, featured: true, badge: 'New',
    specs: { Processor:'AMD Zen 2 + RDNA 2 GPU', Storage:'825GB SSD', Resolution:'Up to 8K', FrameRate:'Up to 120fps' },
  },
  {
    id: 'p3', vendorId: 'v3', vendorHandle: 'SoundLab',
    name: 'Sony WH-1000XM6 Wireless',
    category: 'audio', subcategory: 'Headphones',
    price: 379, priceOld: 429,
    description: 'Industry-leading noise cancellation. 40hr battery, multipoint connect, speak-to-chat.',
    icon: 'fa-headphones', iconColor: 'text-emerald-400',
    rating: 4.95, reviewCount: 1204,
    inStock: true, featured: false, badge: 'Staff Pick',
    specs: { Driver:'30mm dynamic', ANC:'Industry-leading', Battery:'40 hours', Bluetooth:'5.3', Weight:'250g' },
  },
  {
    id: 'p4', vendorId: 'v2', vendorHandle: 'PixelForge',
    name: 'JetBrains All Products Pack',
    category: 'software', subcategory: 'Dev Tools',
    price: 249, priceOld: 329,
    description: '1-year license for all 12 JetBrains IDEs. IntelliJ, WebStorm, PyCharm, DataGrip and more. Instant delivery.',
    icon: 'fa-code', iconColor: 'text-violet-400',
    rating: 4.97, reviewCount: 567,
    inStock: true, featured: false, badge: 'Digital',
    specs: { License:'1-year individual', Products:'12 IDEs', Delivery:'Instant (email)', Platforms:'Win / Mac / Linux' },
  },
  {
    id: 'p5', vendorId: 'v5', vendorHandle: 'DroneWorks',
    name: 'DJI Mavic 4 Pro Fly More',
    category: 'cameras', subcategory: 'Drones',
    price: 2199, priceOld: null,
    description: 'Triple-camera drone with 1" CMOS Hasselblad sensor. 46-min flight time. Fly More kit included.',
    icon: 'fa-helicopter', iconColor: 'text-sky-400',
    rating: 4.93, reviewCount: 234,
    inStock: true, featured: true, badge: 'Premium',
    specs: { Sensor:'1" CMOS Hasselblad', Video:'6K/60fps ProRes', FlightTime:'46 minutes', Range:'20km transmission' },
  },
  {
    id: 'p6', vendorId: 'v1', vendorHandle: 'NovaElectronics',
    name: 'NVIDIA RTX 5090 Founders Ed.',
    category: 'components', subcategory: 'GPUs',
    price: 1999, priceOld: null,
    description: 'Next-gen GPU. 24GB GDDR7, Blackwell architecture for AI-accelerated rendering. Limited stock.',
    icon: 'fa-microchip', iconColor: 'text-amber-400',
    rating: 5.0, reviewCount: 78,
    inStock: false, featured: true, badge: 'Limited',
    specs: { Architecture:'NVIDIA Blackwell', VRAM:'24GB GDDR7', TDP:'575W', Ports:'3x DP 2.1 + HDMI 2.1' },
  },
  {
    id: 'p7', vendorId: 'v6', vendorHandle: 'WearTech',
    name: 'Apple Watch Ultra 3',
    category: 'wearables', subcategory: 'Smartwatches',
    price: 799, priceOld: 849,
    description: 'Titanium case, precision dual-frequency GPS, 72hr battery life. Built for athletes and explorers.',
    icon: 'fa-watch', iconColor: 'text-pink-400',
    rating: 4.88, reviewCount: 423,
    inStock: true, featured: false, badge: null,
    specs: { Case:'Titanium 49mm', GPS:'L1+L5 dual-freq', Battery:'72 hours', WaterResistance:'100m EN13319', OS:'watchOS 12' },
  },
  {
    id: 'p8', vendorId: 'v3', vendorHandle: 'SoundLab',
    name: 'Focusrite Scarlett 4i4 4th Gen',
    category: 'audio', subcategory: 'Interfaces',
    price: 219, priceOld: 249,
    description: 'Studio-grade USB audio interface. 4 ins, 4 outs. Air mode adds vintage preamp character.',
    icon: 'fa-sliders', iconColor: 'text-orange-400',
    rating: 4.91, reviewCount: 788,
    inStock: true, featured: false, badge: null,
    specs: { Inputs:'4 (2 XLR/TRS combo)', Outputs:'4', SampleRate:'192kHz/24-bit', Connection:'USB-C', LoopbackRecording:'Yes' },
  },
]

export const REVIEWS = {
  p1: [
    { id:'r1', user:'dev_marcus', initials:'DM', gradient:'from-purple-500 to-pink-500', rating:5, date:'2 days ago', title:'Perfect workstation for full-stack dev', body:'Runs React/Node, Docker, and still has headroom. OLED display is unreal for 10-hour sessions. Absolutely worth every cent.', likes:31 },
    { id:'r2', user:'ux_claire', initials:'UC', gradient:'from-cyan-500 to-blue-500', rating:5, date:'1 week ago', title:'Figma power users — this is your laptop', body:'Figma, Framer, 40 Chrome tabs simultaneously. OLED reproduction makes color grading accurate. Fast shipping.', likes:22 },
    { id:'r3', user:'sysadmin_k', initials:'SK', gradient:'from-green-500 to-teal-500', rating:4, date:'3 weeks ago', title:'Great but thermal management needs work', body:'Excellent machine overall. Thermals spike under sustained GPU load. Undervolting brought temps down 12C. Battery: 6hrs real-world.', likes:14 },
  ],
  p3: [
    { id:'r4', user:'traveler_99', initials:'TR', gradient:'from-orange-500 to-red-500', rating:5, date:'4 days ago', title:'Best ANC headphones on the market', body:'Plane engines disappear completely. Call quality crystal clear even in busy cafes. Battery life as advertised. Buy without hesitation.', likes:45 },
    { id:'r5', user:'studio_ace', initials:'SA', gradient:'from-teal-500 to-green-500', rating:5, date:'2 weeks ago', title:'Monitoring + commuting in one pair', body:'Good enough for casual studio monitoring and absolutely perfect for daily commuting. The speak-to-chat feature is genuinely magic.', likes:28 },
  ],
}